### ISSUE TITLE
Backup does not work, when a domain has more than one disk

### ISSUE THREAD

**Issue by goetzvr** [Anthony25/virt-backup#16]
I have a domain `backup-test` with one disk `vda`. This one is getting backed up perfectly.
However if I attach a second disk `vdb` the backup fails with:
```
Backup started for domain backup-test
libvirt: QEMU Driver error : internal error: unable to execute QEMU command 'transaction': Could not create file: Permission denied
Traceback (most recent call last):
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/backups/pending.py", line 134, in start
    self._snapshot_and_save_date(definition)
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/backups/pending.py", line 165, in _snapshot_and_save_date
    snapshot_metadatas = self._ext_snapshot_helper.start()
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/backups/snapshot.py", line 48, in start
    snapshot = self.external_snapshot()
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/backups/snapshot.py", line 75, in external_snapshot
    libvirt.VIR_DOMAIN_SNAPSHOT_CREATE_NO_METADATA
  File "/home/kvm/.local/lib/python3.6/site-packages/libvirt.py", line 2584, in snapshotCreateXML
    if ret is None:raise libvirtError('virDomainSnapshotCreateXML() failed', dom=self)
libvirt.libvirtError: internal error: unable to execute QEMU command 'transaction': Could not create file: Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kvm/.local/bin/virt-backup", line 11, in <module>
    sys.exit(cli_run())
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/__main__.py", line 23, in cli_run
    return parse_args_and_run(build_parser())
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/__main__.py", line 103, in parse_args_and_run
    args.func(parsed_args=args)
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/__main__.py", line 119, in start_backups
    main_group.start()
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/groups/pending.py", line 162, in start
    b.start()
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/backups/pending.py", line 151, in start
    self.clean_aborted()
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/backups/pending.py", line 414, in clean_aborted
    self._ext_snapshot_helper.clean()
  File "/home/kvm/.local/lib/python3.6/site-packages/virt_backup/backups/snapshot.py", line 107, in clean
    raise SnapshotNotStarted()
virt_backup.exceptions.SnapshotNotStarted: snapshot not started
```
I tried the following configuration options:
```  
test:
    target: /mnt/backups/test
    autostart: "False"
    hosts:
      - host: backup-test
        disks:
          - vda
```
```
    hosts:
      - host: backup-test
        disks:
          - vda
          - vdb
...
```
    hosts:
      - backup-test
```

**Comment by Anthony25** [comment]
Hi @goetzvr,zfs-auto-snapshot -q -g --label=frequent --keep=4
Thanks a lot for the issue!

I have some hosts with multiple disks, and there is no issue during the backup. Here it seems that you cannot create a new file inside your image directory, what gets you a permission denied. Could you check that please?

**Comment by goetzvr** [comment]
@Anthony25, please put this issue on hold. I encountered similar problems while using `virt-inspector`. Maybe it is really a problem in my setup. I call back later, once I figured out the reason. Thanks for the support so far.

**Comment by Anthony25** [comment]
Ok, no worries, I'm closing this issue for now. Ask me to reopen it if you need to.
